carts/urls.py
from django.urls import path
from . import views
app_name='carts'
urlpatterns=[
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),    
]

cs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='cs_index'),  # 'index'로 수정
    path('report-review/', views.review_report, name='report_review'),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), # 관리자 페이지 URL을 'admin/' 경로로 매핑
    path('users/', include('users.urls')),  # users 앱의 URL을 'users/' 하위 경로로 매핑
    path('', include('home.urls')),     # 홈 페이지 URL을 루트 경로로 매핑 (home 앱과 연결)
    path('cart/', include('carts.urls')), 
    path('reviews/', include('reviews.urls', namespace='reviews')),  # reviews 앱 URLs 추가
    path('shop/', include('shop.urls')),  # shop 앱 URLs 추가 (없다면)
    path('orders/', include('orders.urls', namespace='orders')),  # orders 앱 URLs 추가 (없다면)
    path('benefit/', include('benefit.urls')),
    path('cs/', include('cs.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # 소셜 로그인 URL

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 미디어 파일을 서빙할 수 있도록 설정 (개발 환경에서만 사용)

orders/urls.py
from django.urls import path
from orders import views

app_name = "orders"

urlpatterns=[
    path('create/', views.order_create, name='order_create'), # 주문내역 페이지
]

carts/models.py
from django.db import models
from django.conf import settings

carts/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 101)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    price = forms.FloatField(widget=forms.HiddenInput)  # 가격 필드 추가

carts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from carts.cart import Cart
from shop.models import Product, Category
from carts.forms import CartAddProductForm


@require_POST #post요청만 허용하도록 강제
def cart_add(request, product_id):
    cart = Cart(request) #현재 사용자 세션에 있는 장바구니를 가져오거나 새로운 장바구니 객체를 생성하여 cart에 저장
    product = get_object_or_404(Product, id=product_id) #Product에서 product_id에 해당하는 상품 가져옴
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 price=cd['price'],  # 가격 필드를 넘겨서 할인가가 적용되도록 처리
                 override_quantity=cd['override'])
    return redirect('carts:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('carts:cart_detail')


def cart_detail(request): #장바구니의 상세내용을 보여줌
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
        
    ## 카테고리 ##
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request, 'carts/cart.html', {'cart':cart, 'products': products, 'categories': categories})


def cart_cart(request): #장바구니 페이지를 보여줌
    return render(request, 'carts/cart.html')

carts/templates/carts/cart.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>장바구니</title>
    <link rel="stylesheet" href="{% static 'CARTS_cart.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>

<body>
    <!-- Header -->
    {% include 'common/header.html' %} 

    <!-- cart table -->
           
    <cart class="cart"> 
        <link rel="stylesheet" href="{% static 'cart.css' %}">      
        <h2 class="cart_title">장바구니</h2>
        <div class="inner_cart">
            <table class="cart_table">
                <thead>
                    <tr>
                        <th>제품사진</th>
                        <th>제품명</th> 
                        <th>수량</th>
                        <th>삭제</th>
                        <th>가격</th>                     
                    </tr>
                </thead>

                <tbody>
                    {% for item in cart %}
                        {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                                </a>                                
                            </td> <!--제품사진-->
                            <td>{{ product.name }}</td> <!--제품명-->
                            <td>
                                <form action="{% url 'carts:cart_add' product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="hidden" name="price" value="{{ item.price }}">  <!-- 가격 필드 추가 -->
                                    <input type="submit" value="Update">
                                    {% csrf_token %}
                                </form>                                
                            </td> <!--제품수량-->
                            <td>
                                <form action="{% url 'carts:cart_remove' product.id %}" method="post">
                                    <input type="submit" value="Remove">
                                    {% csrf_token %}
                                </form>                                
                            </td> <!--삭제-->                            
                            <td>{{ item.total_price|floatformat:0|intcomma }}원</td> <!--제품총가격-->

                        </tr>

                        {% endwith %}
                    {% endfor %}
                    <tr class="total">
                        <td colspan="4">총 가격</td>
                        <td>{{ cart.get_total_price|floatformat:0|intcomma }}원</td>
                    </tr>    
                </tbody>
            </table>
        </div>
        <p class="text-right">
            <a href="/" class="button light">쇼핑 계속하기</a>
            
            {% if cart|length > 0 %}
                <!-- 장바구니에 상품이 있을 때만 주문하기 버튼을 활성화 -->
                <a href="{% url 'orders:order_create' %}" class="button">주문하기</a>
            {% else %}
                <!-- 장바구니에 상품이 없을 때 버튼을 비활성화하거나 비표시 -->
                <a href="#" class="button disabled" onclick="return false;">주문하기</a>
            {% endif %}
            
        </p>
    </cart>    

    <!-- footer -->
    {% include 'common/footer.html' %}   
</body>
</html>